"""Node field specifications for the VRML 1.0 parser."""

NODE_FIELD_SPECS: dict[str, dict[str, str]] = {
    "AsciiText": {
        "string": "mfstring",
        "spacing": "float",
        "justification": "enum",
        "width": "float",
    },
    "Cone": {
        "parts": "bitmask",
        "bottomRadius": "float",
        "height": "float",
    },
    "Coordinate3": {"point": "mfvec3"},
    "Cube": {"width": "float", "height": "float", "depth": "float"},
    "Cylinder": {"parts": "bitmask", "radius": "float", "height": "float"},
    "DirectionalLight": {
        "on": "bool",
        "intensity": "float",
        "color": "color",
        "direction": "vec3",
    },
    "FontStyle": {"size": "float", "family": "enum", "style": "enum"},
    "IndexedFaceSet": {
        "coordIndex": "mfint",
        "materialIndex": "mfint",
        "normalIndex": "mfint",
        "textureCoordIndex": "mfint",
    },
    "IndexedLineSet": {"coordIndex": "mfint", "materialIndex": "mfint"},
    "LOD": {"range": "mffloat"},
    "Material": {
        "ambientColor": "mfcolor",
        "diffuseColor": "mfcolor",
        "specularColor": "mfcolor",
        "emissiveColor": "mfcolor",
        "shininess": "mffloat",
        "transparency": "mffloat",
    },
    "MaterialBinding": {"value": "enum"},
    "MatrixTransform": {"matrix": "matrix"},
    "Normal": {"vector": "mfvec3"},
    "NormalBinding": {"value": "enum"},
    "OrthographicCamera": {
        "position": "vec3",
        "orientation": "rotation",
        "focalDistance": "float",
        "nearDistance": "float",
        "farDistance": "float",
        "height": "float",
    },
    "PerspectiveCamera": {
        "position": "vec3",
        "orientation": "rotation",
        "focalDistance": "float",
        "nearDistance": "float",
        "farDistance": "float",
        "heightAngle": "float",
    },
    "PointLight": {
        "on": "bool",
        "intensity": "float",
        "color": "color",
        "location": "vec3",
    },
    "PointSet": {"startIndex": "int", "numPoints": "int"},
    "Rotation": {"rotation": "rotation"},
    "Scale": {"scaleFactor": "vec3"},
    "ShapeHints": {
        "vertexOrdering": "enum",
        "shapeType": "enum",
        "faceType": "enum",
        "creaseAngle": "float",
    },
    "Sphere": {"radius": "float"},
    "SpotLight": {
        "on": "bool",
        "intensity": "float",
        "color": "color",
        "location": "vec3",
        "direction": "vec3",
        "dropOffRate": "float",
        "cutOffAngle": "float",
    },
    "Switch": {"whichChild": "int"},
    "Texture2": {
        "filename": "mfstring",
        "wrapS": "enum",
        "wrapT": "enum",
        "image": "mfint",
    },
    "Texture2Transform": {
        "translation": "vec2",
        "rotation": "float",
        "scaleFactor": "vec2",
        "center": "vec2",
    },
    "Texture2Transformation": {
        "translation": "vec2",
        "rotation": "float",
        "scaleFactor": "vec2",
        "center": "vec2",
    },
    "TextureCoordinate2": {"point": "mfvec2"},
    "Transform": {
        "translation": "vec3",
        "rotation": "rotation",
        "scaleFactor": "vec3",
        "scaleOrientation": "rotation",
        "center": "vec3",
    },
    "Translation": {"translation": "vec3"},
    "WWWAnchor": {"name": "mfstring", "description": "string", "map": "bool"},
    "WWWInline": {
        "name": "mfstring",
        "bboxCenter": "vec3",
        "bboxSize": "vec3",
    },
}
